// <auto-generated />
namespace Migration.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_Table_Epoxys_And_Fluent_Api_For_It : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Table_Epoxys_And_Fluent_Api_For_It));
        
        string IMigrationMetadata.Id
        {
            get { return "202011111304116_Add_Table_Epoxys_And_Fluent_Api_For_It"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
